"""Add Receipt and ReportJob models

Revision ID: 723114ddb74c
Revises: dbc4a90a9429
Create Date: 2026-01-10 12:41:51.222322

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "723114ddb74c"
down_revision: str | Sequence[str] | None = "dbc4a90a9429"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "params_json",
            sa.Text(),
            nullable=False,
            comment="JSON string of report parameters (start_date, end_date, etc.)",
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="reportstatus"),
            nullable=False,
        ),
        sa.Column(
            "s3_key",
            sa.String(length=500),
            nullable=True,
            comment="S3 key of generated PDF (if completed)",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Error message if failed"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_report_jobs_status"), "report_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_report_jobs_user_id"), "report_jobs", ["user_id"], unique=False)
    op.create_table(
        "receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("s3_key", sa.String(length=500), nullable=False, comment="S3 object key (path)"),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False,
            comment="Original uploaded filename",
        ),
        sa.Column(
            "content_type",
            sa.String(length=100),
            nullable=False,
            comment="MIME type (e.g., image/jpeg)",
        ),
        sa.Column("size", sa.BigInteger(), nullable=False, comment="File size in bytes"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_receipts_transaction_id"), "receipts", ["transaction_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_receipts_transaction_id"), table_name="receipts")
    op.drop_table("receipts")
    op.drop_index(op.f("ix_report_jobs_user_id"), table_name="report_jobs")
    op.drop_index(op.f("ix_report_jobs_status"), table_name="report_jobs")
    op.drop_table("report_jobs")
    # ### end Alembic commands ###
