"""Initial migration

Revision ID: 7c3e57455b49
Revises:
Create Date: 2026-01-10 02:04:31.963358

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "7c3e57455b49"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
