"""Initial schema with all models

Revision ID: 9a03dc0c7b31
Revises: 723114ddb74c
Create Date: 2026-01-10 12:54:00.900838

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "9a03dc0c7b31"
down_revision: str | Sequence[str] | None = "723114ddb74c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
