"""Update Transaction model: add currency, note, soft delete, and composite indexes

Revision ID: dbc4a90a9429
Revises: b3f63fc9976a
Create Date: 2026-01-10 12:35:54.998325

"""

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbc4a90a9429"
down_revision: str | Sequence[str] | None = "b3f63fc9976a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add currency column with default value
    op.add_column(
        "transactions",
        sa.Column(
            "currency",
            sa.String(length=3),
            nullable=False,
            server_default="USD",
            comment="ISO 4217 currency code",
        ),
    )
    # Add note column (nullable)
    op.add_column("transactions", sa.Column("note", sa.Text(), nullable=True))
    # Add deleted_at column (nullable)
    op.add_column(
        "transactions",
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Soft delete timestamp",
        ),
    )
    # Add occurred_at column, migrate data from date if it exists
    op.add_column(
        "transactions",
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the transaction actually occurred (UTC)",
        ),
    )
    # Migrate data from date to occurred_at (convert DATE to DATETIME)
    op.execute(
        """
        UPDATE transactions
        SET occurred_at = date::timestamp with time zone
        WHERE occurred_at IS NULL AND date IS NOT NULL
        """
    )
    # Now make occurred_at NOT NULL
    op.alter_column("transactions", "occurred_at", nullable=False)
    # Update amount precision and comment
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        type_=sa.Numeric(precision=15, scale=2),
        comment="Amount in currency units (e.g., 100.50 = $100.50)",
        existing_comment="Amount in currency (positive or negative)",
        existing_nullable=False,
    )
    # Update description type from VARCHAR to TEXT
    op.alter_column(
        "transactions",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    # Drop old date index
    op.drop_index(op.f("ix_transactions_date"), table_name="transactions")
    # Create new indexes
    op.create_index(
        "ix_transactions_active",
        "transactions",
        ["user_id", "occurred_at"],
        unique=False,
        postgresql_where="deleted_at IS NULL",
    )
    op.create_index(
        op.f("ix_transactions_deleted_at"), "transactions", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_occurred_at"), "transactions", ["occurred_at"], unique=False
    )
    op.create_index(
        "ix_transactions_user_category_occurred",
        "transactions",
        ["user_id", "category_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_occurred",
        "transactions",
        ["user_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_type_occurred",
        "transactions",
        ["user_id", "type", "occurred_at"],
        unique=False,
    )
    # Drop old date column
    op.drop_column("transactions", "date")
    # Remove server default from currency (optional, but cleaner)
    op.alter_column("transactions", "currency", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add date column back
    op.add_column(
        "transactions",
        sa.Column(
            "date",
            sa.DATE(),
            autoincrement=False,
            nullable=True,  # Temporarily nullable for data migration
            comment="Transaction date",
        ),
    )
    # Migrate data from occurred_at to date
    op.execute(
        """
        UPDATE transactions
        SET date = occurred_at::date
        WHERE date IS NULL AND occurred_at IS NOT NULL
        """
    )
    # Make date NOT NULL
    op.alter_column("transactions", "date", nullable=False)
    # Drop new indexes
    op.drop_index("ix_transactions_user_type_occurred", table_name="transactions")
    op.drop_index("ix_transactions_user_occurred", table_name="transactions")
    op.drop_index("ix_transactions_user_category_occurred", table_name="transactions")
    op.drop_index(op.f("ix_transactions_occurred_at"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_deleted_at"), table_name="transactions")
    op.drop_index(
        "ix_transactions_active", table_name="transactions", postgresql_where="deleted_at IS NULL"
    )
    # Recreate old date index
    op.create_index(op.f("ix_transactions_date"), "transactions", ["date"], unique=False)
    # Revert description type
    op.alter_column(
        "transactions",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    # Revert amount precision
    op.alter_column(
        "transactions",
        "amount",
        existing_type=sa.Numeric(precision=15, scale=2),
        type_=sa.NUMERIC(precision=10, scale=2),
        comment="Amount in currency (positive or negative)",
        existing_comment="Amount in currency units (e.g., 100.50 = $100.50)",
        existing_nullable=False,
    )
    # Drop new columns
    op.drop_column("transactions", "deleted_at")
    op.drop_column("transactions", "occurred_at")
    op.drop_column("transactions", "note")
    op.drop_column("transactions", "currency")
    # ### end Alembic commands ###
