"""Add user, category, transaction models

Revision ID: f5ecb2774a7a
Revises: 7c3e57455b49
Create Date: 2026-01-10 02:07:23.563347

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f5ecb2774a7a"
down_revision: str | Sequence[str] | None = "7c3e57455b49"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
